[package]
name = "entity"
version = "0.1.0"
edition = "2021"

[dependencies]
sea-orm = { version = "1.1.4" }
uuid = { version = "1.13.1", features = [ "v4", "fast-rng", "macro-diagnostics" ] }
serde = { version = "1.0.217", features = ["derive"] }
